-- ─────────────────────────────────────────────
-- KINETIC — Default Exercise Library
-- Run in Supabase SQL Editor after schema.sql
-- ─────────────────────────────────────────────

insert into public.exercises (name, type, is_default, user_id) values

  -- ── Bodyweight / Calisthenics (reps) ──────────────────────────
  ('Pull-ups',                    'reps', true, null),
  ('Chin-ups',                    'reps', true, null),
  ('Neutral-grip Pull-ups',       'reps', true, null),
  ('Wide-grip Pull-ups',          'reps', true, null),
  ('Archer Pull-ups',             'reps', true, null),
  ('Commando Pull-ups',           'reps', true, null),
  ('Muscle-ups',                  'reps', true, null),
  ('Ring Muscle-ups',             'reps', true, null),
  ('Push-ups',                    'reps', true, null),
  ('Diamond Push-ups',            'reps', true, null),
  ('Wide Push-ups',               'reps', true, null),
  ('Pike Push-ups',               'reps', true, null),
  ('Decline Push-ups',            'reps', true, null),
  ('Archer Push-ups',             'reps', true, null),
  ('Ring Push-ups',               'reps', true, null),
  ('Dips',                        'reps', true, null),
  ('Ring Dips',                   'reps', true, null),
  ('Korean Dips',                 'reps', true, null),
  ('Inverted Rows',               'reps', true, null),
  ('Ring Rows',                   'reps', true, null),
  ('Australian Pull-ups',         'reps', true, null),
  ('Leg Raises',                  'reps', true, null),
  ('Knee Raises',                 'reps', true, null),
  ('Toes to Bar',                 'reps', true, null),
  ('Dragon Flags',                'reps', true, null),
  ('V-ups',                       'reps', true, null),
  ('Sit-ups',                     'reps', true, null),
  ('Crunches',                    'reps', true, null),
  ('Bicycle Crunches',            'reps', true, null),
  ('Squats',                      'reps', true, null),
  ('Jump Squats',                 'reps', true, null),
  ('Pistol Squats',               'reps', true, null),
  ('Bulgarian Split Squats',      'reps', true, null),
  ('Lunges',                      'reps', true, null),
  ('Reverse Lunges',              'reps', true, null),
  ('Step-ups',                    'reps', true, null),
  ('Glute Bridges',               'reps', true, null),
  ('Hip Thrusts',                 'reps', true, null),
  ('Nordic Curls',                'reps', true, null),
  ('Calf Raises',                 'reps', true, null),
  ('Burpees',                     'reps', true, null),
  ('Box Jumps',                   'reps', true, null),
  ('Broad Jumps',                 'reps', true, null),
  ('Mountain Climbers',           'reps', true, null),
  ('Handstand Push-ups',          'reps', true, null),
  ('Wall Walks',                  'reps', true, null),
  ('Skin the Cat',                'reps', true, null),
  ('Back Lever Raises',           'reps', true, null),
  ('Front Lever Raises',          'reps', true, null),

  -- ── Barbell (reps) ────────────────────────────────────────────
  ('Barbell Squat',               'reps', true, null),
  ('Barbell Front Squat',         'reps', true, null),
  ('Barbell Deadlift',            'reps', true, null),
  ('Romanian Deadlift',           'reps', true, null),
  ('Sumo Deadlift',               'reps', true, null),
  ('Barbell Bench Press',         'reps', true, null),
  ('Barbell Incline Bench Press', 'reps', true, null),
  ('Barbell Decline Bench Press', 'reps', true, null),
  ('Barbell Overhead Press',      'reps', true, null),
  ('Barbell Bent-over Row',       'reps', true, null),
  ('Barbell Pendlay Row',         'reps', true, null),
  ('Barbell Hip Thrust',          'reps', true, null),
  ('Barbell Lunge',               'reps', true, null),
  ('Barbell Curl',                'reps', true, null),
  ('Barbell Skull Crushers',      'reps', true, null),
  ('Barbell Good Morning',        'reps', true, null),
  ('Barbell Shrugs',              'reps', true, null),
  ('Barbell Power Clean',         'reps', true, null),
  ('Barbell Snatch',              'reps', true, null),

  -- ── Dumbbell (reps) ───────────────────────────────────────────
  ('Dumbbell Bench Press',        'reps', true, null),
  ('Dumbbell Incline Press',      'reps', true, null),
  ('Dumbbell Flyes',              'reps', true, null),
  ('Dumbbell Incline Flyes',      'reps', true, null),
  ('Dumbbell Shoulder Press',     'reps', true, null),
  ('Dumbbell Lateral Raises',     'reps', true, null),
  ('Dumbbell Front Raises',       'reps', true, null),
  ('Dumbbell Rear Delt Flyes',    'reps', true, null),
  ('Dumbbell Row',                'reps', true, null),
  ('Dumbbell Romanian Deadlift',  'reps', true, null),
  ('Dumbbell Goblet Squat',       'reps', true, null),
  ('Dumbbell Lunges',             'reps', true, null),
  ('Dumbbell Step-ups',           'reps', true, null),
  ('Dumbbell Curl',               'reps', true, null),
  ('Hammer Curl',                 'reps', true, null),
  ('Incline Dumbbell Curl',       'reps', true, null),
  ('Dumbbell Skull Crushers',     'reps', true, null),
  ('Dumbbell Overhead Extension', 'reps', true, null),
  ('Dumbbell Tricep Kickback',    'reps', true, null),
  ('Dumbbell Shrugs',             'reps', true, null),
  ('Dumbbell Calf Raises',        'reps', true, null),

  -- ── Cable (reps) ──────────────────────────────────────────────
  ('Cable Chest Fly',             'reps', true, null),
  ('Cable Row',                   'reps', true, null),
  ('Cable Pulldown',              'reps', true, null),
  ('Cable Curl',                  'reps', true, null),
  ('Cable Tricep Pushdown',       'reps', true, null),
  ('Cable Overhead Extension',    'reps', true, null),
  ('Cable Face Pull',             'reps', true, null),
  ('Cable Lateral Raise',         'reps', true, null),
  ('Cable Woodchop',              'reps', true, null),
  ('Cable Kickback',              'reps', true, null),

  -- ── Machine (reps) ────────────────────────────────────────────
  ('Leg Press',                   'reps', true, null),
  ('Leg Extension',               'reps', true, null),
  ('Leg Curl',                    'reps', true, null),
  ('Seated Leg Curl',             'reps', true, null),
  ('Hip Abduction',               'reps', true, null),
  ('Hip Adduction',               'reps', true, null),
  ('Chest Press Machine',         'reps', true, null),
  ('Pec Deck',                    'reps', true, null),
  ('Shoulder Press Machine',      'reps', true, null),
  ('Lat Pulldown',                'reps', true, null),
  ('Seated Cable Row',            'reps', true, null),
  ('T-Bar Row',                   'reps', true, null),
  ('Smith Machine Squat',         'reps', true, null),
  ('Smith Machine Bench Press',   'reps', true, null),
  ('Preacher Curl',               'reps', true, null),
  ('Machine Curl',                'reps', true, null),
  ('Tricep Dip Machine',          'reps', true, null),
  ('Seated Calf Raise',           'reps', true, null),

  -- ── Kettlebell (reps) ─────────────────────────────────────────
  ('Kettlebell Swing',            'reps', true, null),
  ('Kettlebell Clean',            'reps', true, null),
  ('Kettlebell Snatch',           'reps', true, null),
  ('Kettlebell Press',            'reps', true, null),
  ('Kettlebell Goblet Squat',     'reps', true, null),
  ('Kettlebell Romanian Deadlift','reps', true, null),
  ('Kettlebell Row',              'reps', true, null),
  ('Kettlebell Turkish Get-up',   'reps', true, null),
  ('Kettlebell Windmill',         'reps', true, null),

  -- ── Weighted (bodyweight + load) ──────────────────────────────
  ('Weighted Pull-ups',           'weighted', true, null),
  ('Weighted Chin-ups',           'weighted', true, null),
  ('Weighted Dips',               'weighted', true, null),
  ('Weighted Push-ups',           'weighted', true, null),
  ('Weighted Squats',             'weighted', true, null),
  ('Weighted Lunges',             'weighted', true, null),
  ('Weighted Hip Thrusts',        'weighted', true, null),
  ('Weighted Calf Raises',        'weighted', true, null),
  ('Barbell Back Squat',          'weighted', true, null),
  ('Barbell Deadlift',            'weighted', true, null),
  ('Barbell Bench Press',         'weighted', true, null),
  ('Barbell Overhead Press',      'weighted', true, null),
  ('Barbell Row',                 'weighted', true, null),
  ('Trap Bar Deadlift',           'weighted', true, null),

  -- ── Timed holds / isometrics ──────────────────────────────────
  ('Plank',                       'timed', true, null),
  ('Side Plank',                  'timed', true, null),
  ('Hollow Body Hold',            'timed', true, null),
  ('Arch Body Hold',              'timed', true, null),
  ('Dead Hang',                   'timed', true, null),
  ('Active Hang',                 'timed', true, null),
  ('L-sit',                       'timed', true, null),
  ('V-sit',                       'timed', true, null),
  ('Wall Handstand',              'timed', true, null),
  ('Free Handstand',              'timed', true, null),
  ('Ring Support Hold',           'timed', true, null),
  ('Tuck Front Lever',            'timed', true, null),
  ('Advanced Tuck Front Lever',   'timed', true, null),
  ('Straddle Front Lever',        'timed', true, null),
  ('Full Front Lever',            'timed', true, null),
  ('Tuck Planche',                'timed', true, null),
  ('Advanced Tuck Planche',       'timed', true, null),
  ('Straddle Planche',            'timed', true, null),
  ('Full Planche',                'timed', true, null),
  ('Back Lever',                  'timed', true, null),
  ('Wall Sit',                    'timed', true, null),
  ('Glute Bridge Hold',           'timed', true, null),

  -- ── Cardio (timed) ────────────────────────────────────────────
  ('Running',                     'timed', true, null),
  ('Cycling',                     'timed', true, null),
  ('Jump Rope',                   'timed', true, null),
  ('Rowing Machine',              'timed', true, null),
  ('Elliptical',                  'timed', true, null),
  ('Stair Climber',               'timed', true, null),
  ('Swimming',                    'timed', true, null),
  ('Battle Ropes',                'timed', true, null),
  ('Assault Bike',                'timed', true, null),
  ('Sprint Intervals',            'timed', true, null)

on conflict do nothing;
